config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  get 'page/index'
  root 'page#index'

  get 'search', to: 'dashboard#search'
  post 'search', to: 'dashboard#search_handler'

  get 'show-results', to: 'dashboard#show_results'

  # root 'static#welcome'
  # get 'static/welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :first_name,
            presence: true
  validates :last_name,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Authentications BugFix
  skip_before_filter :verify_authenticity_token, :only => :create

  private
    def current_user
      User.where(id: session[:user_id]).first
    end
  helper_method :current_user
end

app/controllers/dashboard_controller (copy).rb
# ---------- search results module ----------
module SearchAPI
  require 'httparty'
  require 'json'

  url = "https://pixabay.com/api/?key="
  # key = Module.key DO THIS <----------
  key = "2892207-d5872058f9450c1cea591ba03"
  high_res = "&response_group=high_resolution"
  query_search = params[:search_bar].gsub(" ", "+") # ***************************************
  # query = "&q=yellow+flowers&image_type=photo&per_page=200"
  query = "&q=#{query_search}&image_type=photo&per_page=200"

  # response = HTTParty.get(url + key + high_res + query) #requires permission from pixabay
  response = HTTParty.get(url + key + query)
  body = JSON.parse(response.body)

  @hits = body["hits"]

  # puts list of search result urls
  def self.results
    images = []
    i = 0
    while i < @hits.length do
      url = @hits[i]["webformatURL"].gsub("_640.jpg", "_960.jpg")
      images << url
      i += 1
    end
    images
  end
  # search_results = results(hits)
  # p search_results
  # # p body["totalHits"]
end

# ---------- search results Module end ----------
class DashboardController < ApplicationController

include SearchAPI

  def search # get
  end

  def search_handler #post
    search_results = SearchAPI.results
    @@search_results = search_results
    redirect_to show_results_path

  end

  def show_results
    @search_results = @@search_results
  end
end

app/controllers/dashboard_controller.rb
# ---------- search results module ----------
module SearchAPI
  require 'httparty'
  require 'json'

  # puts list of search result urls
  def self.results(params)

    url = "https://pixabay.com/api/?key="
    # key = Module.key DO THIS <----------
    key = "2892207-d5872058f9450c1cea591ba03"
    high_res = "&response_group=high_resolution"
    query_search = params[:search_bar].gsub(" ", "+") # ***************************************
    # query = "&q=yellow+flowers&image_type=photo&per_page=200"
    query = "&q=#{query_search}&image_type=photo&per_page=200"

    # response = HTTParty.get(url + key + high_res + query) #requires permission from pixabay
    response = HTTParty.get(url + key + query)
    body = JSON.parse(response.body)

    hits = body["hits"]

    images = []
    i = 0
    while i < hits.length do
      url = hits[i]["webformatURL"].gsub("_640.jpg", "_960.jpg")
      images << url
      i += 1
    end
    images
  end
  # search_results = results(hits)
  # p search_results
  # # p body["totalHits"]
end

# ---------- search results Module end ----------
class DashboardController < ApplicationController

include SearchAPI

  def search # get
  end

  def search_handler #post
    @search_results = SearchAPI.results(params)
    render "show_results"
  end

  def show_results
    @search_results
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Signed In!'
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged Out'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_url, notice: 'Your account was successfully created!' }
        # format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Your account was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Your account was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashbord_helper.rb
module DashbordHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_search_bar.html.erb
<div id="searchBar">
  <%= form_tag "search", :class => "search-container search-bar" do %>
    <%= text_field_tag "search_bar", nil, placeholder: "What are you looking for?" %>
    <%= button_tag(type: 'submit') do %>
      <%= content_tag(:i, nil, :class => "fa fa-search search-icon") %>
    <% end %>
  <% end %>
</div>

app/views/dashboard/show_results.html.erb
<div class="results-wrapper">
  <ul id="resultImages" class="clean-list">
    <% @search_results.each do | img_url |%>
      <li class="images image-frame"><img src="<%= img_url %>" alt=""></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockBin</title>
    <%= csrf_meta_tags %>

    <!-- Google-Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oswald:400,300,<7></7>00  '
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=<Roboto:400></Roboto:400>,300,<500></500>,700  '
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,700'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,300,700'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Pacifico'
          rel='stylesheet' type='text/css'>
    <!-- Font-Awesome -->
    <link href="https://opensource.keycdn.com/fontawesome/4.6.3/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="header">
      <div id="name">
        <% if current_page?(root_path) %>
          <!-- <h1>Search<span>Bin</span></h1> -->
          <h1><%= link_to "Search\s\sBin", root_path %></h1>
        <% else %>
          <!-- <h2>Search<span>Bin</span></h2> -->
          <h2><%= link_to "Search\s\sBin", root_path %></h2>
        <% end %>
      </div>

      <div id="topSearchBar">
        <% unless current_page?(root_path) %>
          <%= render :partial => 'dashboard/search_bar' %>
        <% end %>
      </div>

      <nav id="user">
        <ul class="clean-list">
          <% if current_user %>
            Signed in as  <%= current_user.email %>
            <li><%= link_to "Sign Out", logout_path %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><span>or</span></li>
            <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <% flash.each do | key, value | %>
      <%= content_tag(:div, class: "alert alert-#{key}") do %>
        <p>
          <%= value %>
        </p>
      <% end %>
    <% end %>

    <%= yield %>

    <footer>
      <p>&copy; <%= Time.now.year%>, Sumware, BFE&nbsp;&nbsp;|&nbsp;&nbsp;<span>SearchBin</span> </p>
    </footer>
  </body>

</html>

app/views/page/index.html.erb
<section id="hero">
  <div id="searchBarBox">
    <h1>Search the Bin</h1>
    <%= render :partial => 'dashboard/search_bar' %>
  </div>
</section>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>